---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/magefiles"
      - "/e2e"
      - "/tools/analyzers"
    schedule:
<<<<<<< HEAD
      interval: "weekly"
=======
      interval: "daily"
>>>>>>> e6f6a832 (RHCLOUD-37468: workflow bootstrapping)
    labels:
      - "area/dependencies"
    groups:
      go-mod:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependencies"
    groups:
      docker:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns: ["*"]
